/// <reference types="@fastly/js-compute" />
// Generated by @sudodevstudio/fastly-for-astro. Do not edit.
//
// Request flow:
//   1. Fastly Compute receives the request.
//   2. PublisherServer tries to serve a published static asset (KV-backed).
//      Returns null if no asset matches.
//   3. Otherwise we hand the request to Astro's SSR handler.
//   4. Security/cache headers are applied inside the SSR handler;
//      static assets get headers from the publisher (and any overrides
//      configured in publish-content.config.js).

import { PublisherServer } from "@fastly/compute-js-static-publish";
import rc from "../static-publish.rc.js";
// AES-GCM polyfill: Astro v6 encrypts server-island props with AES-GCM, but
// Fastly Compute's SubtleCrypto doesn't implement encrypt/decrypt. We install
// at module init AND on every request — Fastly's runtime appears to re-bind
// `crypto.subtle` after the Wizer snapshot is restored, so a one-shot install
// at startup gets clobbered. ensureCryptoPolyfill is a fast sentinel check
// that re-installs only when needed.
import { installCryptoPolyfill, ensureCryptoPolyfill } from "./crypto-polyfill.js";
installCryptoPolyfill();

function installMessageChannelShim() {
  if (typeof globalThis.MessagePort === "undefined") {
    class StubMessagePort {
      constructor() {
        this.onmessage = null;
        this.onmessageerror = null;
        this._peer = null;
        this._started = false;
        this._queue = [];
        this._listeners = new Map();
      }

      postMessage(value) {
        if (!this._peer) return;
        const event = { data: value, ports: [], target: this._peer, type: "message" };
        this._peer._dispatch(event);
      }

      start() {
        this._started = true;
        while (this._queue.length) this._emit(this._queue.shift());
      }

      close() {
        this._peer = null;
        this._queue.length = 0;
      }

      addEventListener(type, listener) {
        if (!this._listeners.has(type)) this._listeners.set(type, []);
        this._listeners.get(type).push(listener);
      }

      removeEventListener(type, listener) {
        const listeners = this._listeners.get(type);
        if (!listeners) return;
        const index = listeners.indexOf(listener);
        if (index >= 0) listeners.splice(index, 1);
      }

      dispatchEvent(event) {
        this._dispatch(event);
        return true;
      }

      _dispatch(event) {
        if (this._started || this.onmessage || (this._listeners.get("message") || []).length) {
          this._emit(event);
        } else {
          this._queue.push(event);
        }
      }

      _emit(event) {
        if (typeof this.onmessage === "function") this.onmessage(event);
        const listeners = this._listeners.get("message") || [];
        for (const listener of listeners) listener.call(this, event);
      }
    }

    globalThis.MessagePort = StubMessagePort;
  }

  if (typeof globalThis.MessageChannel === "undefined") {
    globalThis.MessageChannel = class MessageChannel {
      constructor() {
        this.port1 = new globalThis.MessagePort();
        this.port2 = new globalThis.MessagePort();
        this.port1._peer = this.port2;
        this.port2._peer = this.port1;
      }
    };
  }
}

installMessageChannelShim();

const { handle: astroHandle } = await import(__SERVER_ENTRY_IMPORT__);

const publisherServer = PublisherServer.fromStaticPublishRc(rc);
const ASSETS_PREFIX = __ASSETS_PREFIX__;

addEventListener("fetch", (event) => event.respondWith(handleRequest(event)));

async function handleRequest(event) {
  ensureCryptoPolyfill();
  const request = event.request;
  const url = new URL(request.url);

  let clientAddress;
  let geo;
  try {
    // Fastly's request context exposes client info on event.client (when present).
    clientAddress = event.client && event.client.address ? event.client.address : undefined;
    geo = event.client && event.client.geo ? event.client.geo : undefined;
  } catch {
    // Older runtimes may not have these fields; fall through.
  }

  // Server islands always go to SSR — they're dynamic by definition.
  if (!url.pathname.startsWith("/_server-islands/")) {
    try {
      const staticResponse = await publisherServer.serveRequest(request);
      if (staticResponse) {
        return enforceSafeStaticHeaders(staticResponse, url);
      }
    } catch (err) {
      // Static lookup failures should not take down the SSR path.
      console.error("static publisher error", err && err.message ? err.message : err);
    }
  }

  return astroHandle(request, { clientAddress, geo, fastlyEvent: event });
}

function enforceSafeStaticHeaders(response, url) {
  // Don't override headers the static publisher already set, but ensure we
  // never leak Set-Cookie from a static response (which would be unexpected).
  if (response.headers.has("set-cookie")) {
    const headers = new Headers(response.headers);
    headers.delete("set-cookie");
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  }
  void url;
  return response;
}
