// Generated by @sudodevstudio/fastly-for-astro. Do not edit by hand.
// Drives both `publish-content` uploads and PublisherServer's runtime serving.

const config = {
  rootDir: __ROOT_DIR__,
  excludeDirs: ["node_modules"],
  excludeDotfiles: true,
  includeWellKnown: true,
  // Upload everything from the Astro client output to KV.
  kvStoreAssetInclusionTest: () => true,
  contentCompression: __COMPRESSION__,
  server: {
    publicDir: __ROOT_DIR__,
    // Astro emits trailing-slash directories with index.html for prerendered routes.
    autoIndex: ["index.html"],
    autoExt: [".html"],
    // Astro hashed assets live under the assetsPrefix; treat as static.
    staticItems: [__ASSETS_PREFIX__],
    allowedEncodings: ["br", "gzip"],
    notFoundPageFile: "/404.html",
  },
};

export default config;
