// Generated by @sudodevstudio/fastly-for-astro. Do not edit by hand.
// See: https://github.com/fastly/compute-js-static-publish

const rc = {
  kvStoreName: __KV_STORE_NAME__,
  defaultCollectionName: __DEFAULT_COLLECTION__,
  publishId: __PUBLISH_ID__,
  staticPublisherWorkingDir: __WORKING_DIR__,
};

export default rc;
